var grv=window.grv={};grv.exportSymbol=function(a,c){for(var b=a.split("."),d=window,e=0;e<b.length-1;e++)d=d[b[e]];d[b[b.length-1]]=c};var config=window.grvConfig||{},extend=function(a,c){var b;if(a&&c){for(b in c)a[b]=c[b];return a}},config=extend(config,{namespace:"grv.objects"});(function(){for(var a=config.namespace.split("."),c=window,b=0;b<a.length;b++)void 0===c[a[b]]&&(c[a[b]]={}),c=c[a[b]];grv.generatedNamespace=c})();grv.getGeneratedNamespaceObj=function(){return grv.generatedNamespace};
grv.exportSymbol("grv",grv);grv.RowState={INVALID:0,UNCHANGED:2,ADDED:4,DELETED:8,MODIFIED:16};grv.exportSymbol("grv.RowState",grv.RowState);
grv.DateParser=function(){this.deserialize=function(a){if("string"===typeof a&&0===a.indexOf("/Date(")){var c=0;-1===a.indexOf("-")&&(c=(new Date).getTimezoneOffset());a=new Date(parseInt(a.substr(6)));0<c&&a.setMinutes(a.getMinutes()+c)}return a};this.serialize=function(a){return"/Date("+Date.UTC(a.getFullYear(),a.getMonth(),a.getDate(),a.getHours(),a.getMinutes(),a.getSeconds(),0)+")/"}};grv.getType=function(a){return grv.getGeneratedNamespaceObj()[a]};
grv.clearTypes=function(){grv.generatedNamespace={}};grv.onError=ko.observable({});grv.onError.subscribe(function(a){throw JSON.stringify(a);});grv.isArray=function(a){a=ko.utils.unwrapObservable(a);return!a?!1:a.isArray||"[object Array]"===Object.prototype.toString.call(a)};grv.objectKeys=Object.keys||function(a){for(var c in a)rorm.push(c);return[]};
grv.isGroovsterCollection=function(a){var c=!1;void 0!==a&&void 0!==a.grv&&void 0!==a.grv.___GroovsterCollection___?c=!0:grv.isArray(a)&&0<a.length&&a[0].hasOwnProperty("RowState")&&(c=!0);return c};grv.isGroovsterEntity=function(a){var c=!1;void 0!==a&&(void 0!==a.grv&&void 0!==a.grv.___GroovsterEntity___)&&(c=!0);return c};grv.isGroovsterLazyLoader=function(a){var c=!1;void 0!==a&&(void 0!==a.grv&&void 0!==a.grv.___GroovsterLazyLoad___)&&(c=!0);return c};
grv.exportSymbol("grv.isGroovsterCollection",grv.isGroovsterCollection);
var utils={dateParser:new grv.DateParser,copyDataIntoEntity:function(a,c){var b,d;if(a&&c){for(b in a)if(c.hasOwnProperty(b)&&(!a.grvTypeDefs||!a.grvTypeDefs[b]))if(d=c[b],"string"===typeof d&&(d=utils.dateParser.deserialize(d)),ko.isObservable(a[b]))a[b](d);else a[b]=d;return a}},extend:function(a,c){var b;if(a&&c){for(b in c)a[b]=c[b];return a}},addPropertyChangedHandlers:function(a,c){var b=a[c];ko.isObservable(b)&&(!(b instanceof Array)&&b.__ko_proto__!==ko.dependentObservable)&&b.subscribe(function(b){var e;
!1===a.grv.ignorePropertyChanged&&(e=a.grvColumnMap[c],1===e&&(e=c),e=e||c,-1===ko.utils.arrayIndexOf(a.ModifiedColumns(),e)&&(a.grv.originalValues[c]||(a.grv.originalValues[c]=b),"RowState"!==c&&(a.ModifiedColumns.push(e),a.RowState()!==grv.RowState.MODIFIED&&a.RowState()!==grv.RowState.ADDED&&a.RowState(grv.RowState.MODIFIED))))},a,"beforeChange")},startTracking:function(a){var c;a.hasOwnProperty("RowState")?ko.isObservable(a.RowState)||(a.RowState=ko.observable(a.RowState)):a.RowState=ko.observable(grv.RowState.ADDED);
a.hasOwnProperty("ModifiedColumns")?a.ModifiedColumns([]):a.ModifiedColumns=ko.observableArray();for(c in a)if("ModifiedColumns"!==c&&"__type"!==c&&"grvExtendedData"!==c&&"grv"!==c){var b=a[c];b instanceof Array||a.hasOwnProperty(c)&&ko.isObservable(b)&&utils.addPropertyChangedHandlers(a,c)}return a},expandExtraColumns:function(a,c){var b,d,e=c||!1;if(a.grvExtendedData&&grv.isArray(a.grvExtendedData)){b=ko.isObservable(a.grvExtendedData)?a.grvExtendedData():a.grvExtendedData;for(d=0;d<b.length;d++)if(ko.isObservable(a[b[d].Key]))a[b[d].Key](b[d].Value);
else a[b[d].Key]=e?ko.observable(b[d].Value):b[d].Value;delete a.grvExtendedData}return a},getDirtyGraph:function(a,c,b){var d,e,f,g;if(void 0===c&&!a.isDirtyGraph())return null;if(grv.isGroovsterEntity(a))for(d in grv.isArray(b)?(e=a.prepareForJSON(),b.push(e),b=e):b=a.prepareForJSON(),void 0===c&&(c=b),a.grvTypeDefs){if(void 0!==a[d]&&a[d].isDirtyGraph()){f=a[d].prepareForJSON();b[d]=[];for(g=0;g<f.length;g++)e=f[g],grv.utils.getDirtyGraph(e,c,b[d])}}else{c=[];f=a.prepareForJSON();for(g=0;g<f.length;g++)e=
f[g],grv.utils.getDirtyGraph(e,c,c)}return c}};utils.newId=function(){var a=(new Date).getTime();return function(){return++a}}();grv.utils=utils;grv.exportSymbol("grv.extend",grv.extend);grv.exportSymbol("grv.startTracking",grv.startTracking);grv.exportSymbol("grv.getDirtyGraph",grv.getDirtyGraph);grv.PagerFilterCriteria=function(){this.operation=this.criteria2=this.criteria1=this.column=null;this.conjuction="AND"};grv.PagerSortCriteria=function(){this.column=null;this.direction="ASC"};
grv.PagerRequest=function(){this.getTotalRows=!0;this.totalRows=0;this.pageSize=20;this.pageNumber=1;this.filterCriteria=this.sortCriteria=null};grv.grvLazyLoader=function(a,c){return function(){var b;if(0===arguments.length){if(void 0===b){b=a.createObjectFromType(a.grvTypeDefs[c]);if(void 0===b)throw"Please include the JavaScript class file for the '"+type+"'";b.load({route:a.grvRoutes[c],data:a.grvPrimaryKeys()})}a[c]=b;return"collection"===a.grvRoutes[c].response?b():b}}};
grv.grvLazyLoader.fn={__ko_proto__:ko.observable,isDirty:function(){return!1},isDirtyGraph:function(){return!1},subscribe:function(){}};grv.defineLazyLoader=function(a,c){var b=function(){return(new grv.grvLazyLoader(a,c))()};ko.utils.extend(b,grv.grvLazyLoader.fn);b.grv={};b.grv.___GroovsterLazyLoader___=!0;return b};
grv.GroovsterEntity=function(){var a=[];this.customize=function(c){a.push(c);return this};this.init=function(){var c=this;c.grv.___GroovsterEntity___=grv.utils.newId();c.grv.ignorePropertyChanged=!1;c.grv.originalValues={};c.grv.isLoading=ko.observable(!1);grv.utils.startTracking(c);ko.utils.arrayForEach(a,function(a){a&&a.call(c)});this.isDirty=ko.computed(function(){return c.RowState()!==grv.RowState.UNCHANGED});this.isDirtyGraph=function(){var a,d=!1;if(c.RowState()!==grv.RowState.UNCHANGED)return!0;
for(a in this.grvTypeDefs)if(void 0!==this[a]&&(d=this[a].isDirtyGraph(),!0===d))break;return d}};this.createObjectFromEsTypeDef=function(a){var b;this.grvTypeDefs&&this.grvTypeDefs[a]&&(a=grv.getType(this.grvTypeDefs[a]))&&(b=new a);return b};this.createObjectFromType=function(a){var b;(a=grv.getType(a))&&(b=new a);return b};this.prepareForJSON=function(){var a=this,b={};ko.utils.arrayForEach(grv.objectKeys(this),function(d){var e;switch(d){case "grv":case "grvTypeDefs":case "grvRoutes":case "grvColumnMap":case "grvExtendedData":break;
case "RowState":b.RowState=ko.utils.unwrapObservable(a.RowState);break;case "ModifiedColumns":b.ModifiedColumns=ko.utils.unwrapObservable(a.ModifiedColumns);break;default:if(void 0!==a.grvColumnMap[d]&&(e=ko.utils.unwrapObservable(a[d]),null===e||!grv.isGroovsterCollection(e)&&"function"!==typeof e&&void 0!==e))b[d]=null!==e&&e instanceof Date?utils.dateParser.serialize(e):e}});return b};this.populateEntity=function(a){var b,d,e;this.grv.ignorePropertyChanged=!0;try{for(b in this.hasOwnProperty("ModifiedColumns")?
this.ModifiedColumns([]):this.ModifiedColumns=ko.observableArray(),this.grv.originalValues={},grv.utils.copyDataIntoEntity(this,a),grv.utils.expandExtraColumns(this,!0),a)if(a.hasOwnProperty(b)&&this.grvTypeDefs&&this.grvTypeDefs[b])if(d=grv.getType(this.grvTypeDefs[b]))if(e=new d,e.grv.hasOwnProperty("___GroovsterCollection___")?e.populateCollection(a[b]):e.populateEntity(a[b]),grv.isGroovsterCollection(this[b]))this[b](e());else this[b]=e;else grv.isArray(a[b])?(this[b]=a[b],ko.utils.arrayForEach(this[b],
function(){})):this[b]=a[b]}finally{this.grv.ignorePropertyChanged=!1}};this.applyDefaults=function(){};this.acceptChanges=function(){this.grv.originalValues={};this.ModifiedColumns([]);this.grv.ignorePropertyChanged=!0;this.RowState(grv.RowState.UNCHANGED);this.grv.ignorePropertyChanged=!1};this.rejectChanges=function(){var a;if(this.grv.originalValues){this.grv.ignorePropertyChanged=!0;for(a in this.grv.originalValues)this[a](this.grv.originalValues[a]);this.ModifiedColumns([]);this.grv.originalValues=
{};this.grv.ignorePropertyChanged=!1}};this.markAsDeleted=function(){this.hasOwnProperty("RowState")?this.RowState()!==grv.RowState.DELETED&&this.RowState(grv.RowState.DELETED):this.RowState=ko.observable(grv.RowState.DELETED);this.hasOwnProperty("ModifiedColumns")&&this.ModifiedColumns.removeAll()};this.load=function(a){var b={},d=this;d.grv.isLoading(!0);b.wasLoaded=!1;b.state=a.state;a.async=void 0!==a.success||void 0!==a.error?!0:!1;a.route&&(a.url=a.route.url||this.grvRoutes[a.route].url,a.type=
a.route.method||this.grvRoutes[a.route].method);var e=a.success,f=a.error;a.success=function(a){void 0!==a&&null!==a&&(b.wasLoaded=!0,d.populateEntity(a));e&&e.call(d,a,b);d.grv.isLoading(!1)};a.error=function(a,c){f&&f.call(d,a,c,b);d.grv.isLoading(!1)};grv.dataProvider.execute(a);!1===a.async&&d.grv.isLoading(!1);return b.wasLoaded};this.loadByPrimaryKey=function(a,b,d,e){var f={route:this.grvRoutes.loadByPrimaryKey};1===arguments.length&&arguments[0]&&"object"===typeof arguments[0]?grv.utils.extend(f,
arguments[0]):(f.data=a,f.success=b,f.error=d,f.state=e);return this.load(f)};this.save=function(a,b,d){var e=this;e.grv.isLoading(!0);var f={success:a,error:b,state:d,route:e.grvRoutes.commit};switch(e.RowState()){case grv.RowState.ADDED:f.route=e.grvRoutes.create||f.route;break;case grv.RowState.MODIFIED:f.route=e.grvRoutes.update||f.route;break;case grv.RowState.DELETED:f.route=e.grvRoutes["delete"]||f.route}1===arguments.length&&(arguments[0]&&"object"===typeof arguments[0])&&grv.utils.extend(f,
arguments[0]);f.async=void 0!==f.success||void 0!==f.error?!0:!1;f.data=grv.utils.getDirtyGraph(e);if(null===f.data)!0===f.async&&f.success(null,f.state),e.grv.isLoading(!1);else{f.route&&(f.url=f.route.url,f.type=f.route.method);var g=f.success,h=f.error;f.success=function(a,b){e.populateEntity(a);g&&g.call(e,a,b.state);e.grv.isLoading(!1)};f.error=function(a,b,c){h&&h.call(e,a,b,c.state);e.grv.isLoading(!1)};grv.dataProvider.execute(f);!1===f.async&&e.grv.isLoading(!1)}}};
grv.exportSymbol("grv.GroovsterEntity",grv.GroovsterEntity);grv.exportSymbol("grv.GroovsterEntity.populateEntity",grv.GroovsterEntity.populateEntity);grv.exportSymbol("grv.GroovsterEntity.markAsDeleted",grv.GroovsterEntity.markAsDeleted);grv.exportSymbol("grv.GroovsterEntity.load",grv.GroovsterEntity.load);grv.exportSymbol("grv.GroovsterEntity.loadByPrimaryKey",grv.GroovsterEntity.loadByPrimaryKey);grv.exportSymbol("grv.GroovsterEntity.save",grv.GroovsterEntity.save);
grv.GroovsterEntityCollection=function(){var a=ko.observableArray([]);a.grv={};ko.utils.extend(a,grv.GroovsterEntityCollection.fn);a.grv.___GroovsterCollection___=grv.utils.newId();a.grv.deletedEntities=new ko.observableArray;a.grv.deletedEntities([]);a.grv.isLoading=ko.observable(!1);return a};
grv.GroovsterEntityCollection.fn={filter:function(a){var c=this();return ko.utils.arrayFilter(c,a)},prepareForJSON:function(){var a=[];ko.utils.arrayForEach(this(),function(c){c.isDirtyGraph()&&a.push(c)});ko.utils.arrayForEach(this.grv.deletedEntities(),function(c){c.RowState()!==grv.RowState.ADDED&&a.push(c)});return a},acceptChanges:function(){ko.utils.arrayForEach(this(),function(a){a.RowState()!==grv.RowState.UNCHANGED&&a.acceptChanges()});this.grv.deletedEntities([])},rejectChanges:function(){var a=
[],c=0,b=0,d;ko.utils.arrayForEach(this.grv.deletedEntities(),function(e){e.RowState()===grv.RowState.ADDED?(a[c]=b,c+=1):e.rejectChanges();b+=1});if(0<a.length)for(b=a.length-1;0<=b;b--)this.grv.deletedEntitigrv.splice(a[b],1);a=[];ko.utils.arrayForEach(this(),function(b){switch(b.RowState()){case grv.RowState.MODIFIED:b.rejectChanges();break;case grv.RowState.ADDED:a.push(b)}});if(0<a.length)for(d=0;d<a.length;d++)b=ko.utils.arrayIndexOf(this(),a[d]),0<=b&&this.splice(b,1);0<this.grv.deletedEntities().length&&
(d=this().concat(this.grv.deletedEntities()),this(d));this.grv.deletedEntities([])},markAllAsDeleted:function(){var a,c,b,d;this.grv.deletedEntities(this.splice(0,this().length));b=this.grv.deletedEntities;d=b().length;for(a=0;a<d;a+=1)c=b()[a],c.RowState()===grv.RowState.UNCHANGED&&(c.hasOwnProperty("RowState")?c.RowState()!==grv.RowState.DELETED&&c.RowState(grv.RowState.DELETED):c.RowState=ko.observable(grv.RowState.DELETED),c.hasOwnProperty("ModifiedColumns")&&c.ModifiedColumns.removeAll())},markAsDeleted:function(a){var c,
b,d,e;b=[];if(!arguments)throw Error("The entitiesOrEntityToDelete cannot be null or undefined.");if(grv.isArray(a)){if(b=ko.utils.unwrapObservable(a),0===b.length)throw Error("The array passed in to markAsDeleted.markAsDeleted() cannot be empty.");}else for(c=0;c<arguments.length;c++)if(grv.isGroovsterEntity(arguments[c]))b.push(arguments[c]);else throw Error("Invalid type passed in to markAsDeleted.markAsDeleted()");c=this.grv.deletedEntities().concat(b);this.grv.deletedEntities(c);this.removeAll(b);
d=this.grv.deletedEntities;e=d().length;for(c=0;c<e;c+=1)b=d()[c],b.RowState()===grv.RowState.UNCHANGED&&(b.hasOwnProperty("RowState")?b.RowState()!==grv.RowState.DELETED&&b.RowState(grv.RowState.DELETED):b.RowState=ko.observable(grv.RowState.DELETED),b.hasOwnProperty("ModifiedColumns")&&b.ModifiedColumns.removeAll())},populateCollection:function(a){var c=this.grv.entityTypeName,b,d=[],e=this.createEntity,f;c&&(b=grv.getType(c));a&&grv.isArray(a)&&(ko.utils.arrayForEach(a,function(a){f=e(a,b);void 0!==
f&&null!==f&&d.push(f)}),this(d))},createEntity:function(a,c){var b;b=c;c||(b=this.grv.entityTypeName,b=grv.getType(b));b?(b=new b,b.populateEntity(a)):b=a;return b},addNew:function(){var a=null,c=this.grv.entityTypeName;c&&(a=grv.getType(c),a=new a,this.push(a));return a},load:function(a){var c=this;c.grv.isLoading(!0);a.async=void 0!==a.success||void 0!==a.error?!0:!1;a.route&&(a.url=a.route.url||this.grvRoutes[a.route].url,a.type=a.route.method||this.grvRoutes[a.route].method);var b=a.success,
d=a.error;a.success=function(a,d){c.populateCollection(a);b&&b.call(c,a,d.state);c.grv.isLoading(!1)};a.error=function(a,b,g){d&&d.call(c,a,b,g.state);c.grv.isLoading(!1)};grv.dataProvider.execute(a);!1===a.async&&c.grv.isLoading(!1)},loadAll:function(a,c,b){var d={route:this.grvRoutes.loadAll};1===arguments.length&&arguments[0]&&"object"===typeof arguments[0]?grv.utils.extend(d,arguments[0]):(d.success=a,d.error=c,d.state=b);this.load(d)},save:function(a,c,b){var d=this;d.grv.isLoading(!0);var e=
{success:a,error:c,state:b,route:d.grvRoutes.commit};1===arguments.length&&(arguments[0]&&"object"===typeof arguments[0])&&grv.utils.extend(e,arguments[0]);e.async=void 0!==e.success||void 0!==e.error?!0:!1;e.data=grv.utils.getDirtyGraph(d);if(null===e.data){if(!1===e.async){d.grv.isLoading(!1);return}e.success(null,e)}e.route&&(e.url=e.route.url,e.type=e.route.method);var f=e.success,g=e.error;e.success=function(a,b){d.grv.deletedEntities([]);d.populateCollection(a);f&&f.call(d,a,b.state);d.grv.isLoading(!1)};
e.error=function(a,b,c){g&&g.call(d,a,b,c.state);d.grv.isLoading(!1)};grv.dataProvider.execute(e);!1===e.async&&d.grv.isLoading(!1)}};grv.exportSymbol("grv.GroovsterEntityCollection",grv.GroovsterEntityCollection);grv.exportSymbol("grv.GroovsterEntityCollection.markAllAsDeleted",grv.GroovsterEntityCollection.markAllAsDeleted);grv.exportSymbol("grv.GroovsterEntityCollection.loadAll",grv.GroovsterEntityCollection.loadAll);grv.exportSymbol("grv.GroovsterEntityCollection.load",grv.GroovsterEntityCollection.load);
grv.exportSymbol("grv.GroovsterEntityCollection.save",grv.GroovsterEntityCollection.save);grv.defineEntity=function(a,c){var b="string"!==typeof a,d=b?a:c,e=function(a){this.grv={};d.call(this);this.applyDefaults();this.init();a&&this.populateEntity(a)};e.prototype=new grv.GroovsterEntity;b||(grv.generatedNamespace[a]=e);return e};grv.exportSymbol("grv.defineEntity",grv.defineEntity);
grv.defineCollection=function(a,c){var b="string"!==typeof a,d=b?a:c,e=function(a){var b=new grv.GroovsterEntityCollection;b.grv.entityTypeName=d;this.init.call(b);a&&b.populateCollection(a);return b};e.prototype=new function(){var a=this,b=[];this.init=function(){var c=this;ko.utils.arrayForEach(b,function(a){a.call(c)});for(var d in a)a.hasOwnProperty(d)&&("init"!==d&&"customize"!==d)&&(c[d]=a[d]);this.isDirty=function(){var a,b,d=c(),e=!1;if(0<this.grv.deletedEntities().length)e=!0;else if(0<d.length&&
d[d.length-1].isDirty())e=!0;else for(a=0;a<d.length;a++)if(b=d[a],b.RowState()!==grv.RowState.UNCHANGED){e=!0;break}return e};this.isDirtyGraph=function(){var a,b,d=c();b=!1;if(0<this.grv.deletedEntities().length)b=!0;else if(0<d.length&&d[d.length-1].isDirty())b=!0;else for(a=0;a<d.length;a++)if(b=d[a],b.RowState()!==grv.RowState.UNCHANGED){b=!0;break}else if(b=b.isDirtyGraph(),!0===b)break;return b}};this.customize=function(a){b.push(a)}};b||(grv.generatedNamespace[a]=e);return e};
grv.exportSymbol("grv.defineCollection",grv.defineCollection);
grv.AjaxProvider=function(){var a=function(){};this.execute=function(c){var b=c.success||a,d=c.error||a;c=$.extend({cache:!1,contentType:"application/json; charset=utf-8;",dataType:"json",type:"GET"},c);c.success=function(a){b(a,c)};c.error=function(a){if(d)d(a.status,a.responseText,c);else grv.onError({code:a.status,message:a.responseText})};var e=c,f;var g=c.data;f=/\{([^\}]+)\}/g;f="string"===typeof g?void 0:c.url.replace(f,function(a,b){if(b in g)return ko.utils.unwrapObservable(g[b])});e.url=
f;c.data&&"GET"!==c.type&&(c.data=ko.toJSON(c.data));$.ajax(c)}};grv.dataProvider=new grv.AjaxProvider;
